#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# CHANGE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Updating systemd configuration..."

if [ $change_path -eq 1 ]
then
    ynh_replace --match="--baseurl=$old_path" --replace="--baseurl=$new_path" --file="/etc/systemd/system/$app.service"
    systemctl daemon-reload
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Server running at"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
