#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu


# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)



# Remove sources
sudo rm -rf "/var/www/$app"

# Remove nginx configuration file
[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

sudo systemctl daemon-reload

# Remove monitor
sudo yunohost service remove "$app"

# Reload nginx service
sudo systemctl reload nginx.service
